#snakemake -np --use-singularity 

configfile: "config/config.yaml" 

rule all: 
	input:
		expand("results/{sample}.merged.vcf", sample=config["samples"])

rule retro:
	input:
		sample="{sample}.bam", 
		ref=expand("{ref_retro}", ref_retro=config["ref_retro"]),
		ref_fasta=expand("{ref_fasta}", ref_fasta=config["ref_fasta"])
	output:
		discover="results/{sample}.output.vcf", 
		call="results/{sample}.final.vcf"
	container: 
		"docker://kristinebilgrav/findtroll:latest"
	script:
		"bash run_retro.sh {input.sampleinput.sample} {output.discover} {input.ref} {output.discover} {input.ref_fasta} {output.call}"

rule jitter:
	input:
		sample="{sample}.bam", 
		ref=expand("{ref_jitter}", ref_jitter=config["ref_jitter"])
	output:
		"results/{sample}_jitter.vcf"
	container: 
		"docker://kristinebilgrav/findtroll:latest"
	shell:
		"python jitterbug.py {input.sample} {input.ref} -o {output}"

rule tiddit:
	input:
		sample="{sample}.bam",
		ref=expand("{ref_tiddit}", ref_tiddit=config["ref_tiddit"])
	output:
		"results/{sample}_tiddit.vcf"
	container: 
		"docker://kristinebilgrav/findtroll:latest"
	shell:
		"python TIDDIT.py --sv --bam {input.sample} --ref {input.ref} -o {output}"

rule mobileann:
	input:
		tiddit="results/{sample}_tiddit.vcf", 
		retro="results/{sample}.final.vcf"
	output:
		"results/{sample}_tiddit_retro.vcf"
	container: 
		"docker://kristinebilgrav/findtroll:latest"
	shell:
		"python MobileAnn.py --sv_annotate --sv {input.tiddit} --db {input.retro} > {output}"

rule svdb_merge:
	input:
		retro="results/{sample}.final.vcf",
		tiddit_retro="results/{sample}_tiddit_retro.vcf",
		jitter="results/{sample}_jitter.vcf"
	output:
		"results/{sample}.merged.vcf"
	container: 
		"docker://kristinebilgrav/findtroll:latest"
	shell:
		"svdb --merge --vcf {input.retro} {input.tiddit_retro} {input.jitter} > {output}"


#rule vep:
	#input:
		#"results/{sample}.merged.vcf"
	#output:
		#"results/{sample}.merged.vep.vcf"
	#shell:
		#"path/to/vep "

#rule annotate:
	#input:
		#"results/{sample}.merged.vep.vcf"
	#output:
		#"results/{sample}.merged.vep.annotated.vcf"
	#script:
		#"scripts/run_annotate.py {input} {output}"


