ME_db: path/to/db
libstats_jitter: <libstats/jitter>
ref_ME_bed: <>
ref_ME_gff3: <gff/MEs/ingenome>
ref_ME_tab: <path/to/tabfile/wpaths/toMEbedfiles>
ref_fasta: <path/to/ref/fastafile>
samples:
  SweGen3333: samples/SweGen3333.bam
vep_assembly: GRCh38
vep_basedir: $VEP_CACHE
vep_custom: <path/to/file,short_name,file_type,annotation_type,report_coordinates,vcf_fields>
vep_path: module load bioinfo-tools vep |
