ref_fasta: resources/reference38/hg.fasta
ref_jitter: resources/reference38/jitter.tab
ref_retro: resources/reference38/retro.tab
ref_tiddit: resources/reference38/tiddit.tab
samples:
  SweGen3333: samples/SweGen3333.bam
vep_path: module load bioinfo-tools vep |
