ref_fasta: reference/hg.fasta
ref_jitter: reference/jitter.tab
ref_retro: reference/retro.tab
ref_tiddit: reference/tiddit.tab
samples:
  SweGen003: samples/SweGen003.bam

vep_path: "module load bioinfo-tools vep |" #or path/to/vep
